### ISSUE TITLE
MVP PRIORITY - Home Page

### ISSUE THREAD

**Issue by dillonhealybtc** [Tribe-BTC/tribe-master#42]
Create a simple home landing page. Can essentially be the old version we had with two button options, one leading to the "join bitpac" aggregation page (to be made), and the other leading to "create bitpac" page (currently the homepage). Can also have our logo and tagline "Bitcoin Publicly Auditable Cooperatives" and in the future we'll add a few main graphs showing total bitpacs made, TVL, statements passed etc.

**Comment by andredevjs** [comment]
@dillonhealybtc I think the landing page, must be more informative about the product, I think a good example of a good landing page for a product like this one will be https://www.bitgo.com/
It has several things that allows anyone to understand what the project is about, who we can serve with our solution, a list of features that we offer, etc. And then have some call to actions to our app and to the dashboard you mention. Something like this will be useful to be able to position the website on google, and have a better onboarding of people.
